version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: project-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    deploy:
      resources:
        limits:
          # cpus: '0.5'  # Giới hạn sử dụng CPU
          # cpu_quota: 50000     # Giới hạn CPU (50ms)
          # cpu_period: 100000    # Thời gian chu kỳ (100ms)
          memory: 512M  # Giới hạn sử dụng RAM
          # memswap_limit: 1G        # Giới hạn swap tổng (RAM + swap)


  backend:
    build:
      context: ./BE_Node
    container_name: project-backend
    ports:
      - "8000:8000"
    volumes:
      - ./BTL_BE_Node/:/app
    links:
      - mongo
    depends_on:
      - mongo
    deploy:
      resources:
        limits:
          # cpus: '0.5'  # Giới hạn sử dụng CPU
          # cpu_quota: 50000   # Giới hạn CPU (50ms)
          # cpu_period: 100000   # Thời gian chu kỳ (100ms)
          memory: 1G  # Giới hạn sử dụng RAM
          # memswap_limit: 1G        # Giới hạn swap tổng (RAM + swap)

  frontend:
    build:
      context: ./nckh-fe
    container_name: project-frontend
    ports:
      - "3000:80"  # Chỉnh sửa port để phù hợp với Nginx
    volumes:
      - ./nckh-fe/:/app
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          # cpus: '0.5'  # Giới hạn sử dụng CPU
          # cpu_quota: 50000     # Giới hạn CPU (50ms)
          # cpu_period: 100000   # Thời gian chu kỳ (100ms)
          memory: 512M  # Giới hạn sử dụng RAM
          # memswap_limit: 1G        # Giới hạn swap tổng (RAM + swap)

volumes:
  mongo-data:
